name: Send to Adora

on:
  push:
    branches:
      - '**'

jobs:
  
  notify:
    
    name: Notify Adora
    runs-on: ubuntu-latest

    steps:

      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_type: 'json-extended'
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: s3cr4t
          data: '{ "eventType": "SHIP", "env" : "staging" }'
