name: Branch Created

on:
  create:
    branches:
      - '**'

jobs:
  
  notify:
    
    name: Notify Adora
    runs-on: ubuntu-latest

    steps:

      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_type: 'json'
          webhook_url: ${{ secrets.WEBHOOK_HACK_URL }}
          webhook_secret: s3cr4t
          data: '{"ref":"${{github.event.ref}}", "eventType": "START_CYCLE", "name" : "Coding Time" }'
