name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Invoke deployment hook
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12s
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "payments-prodoops"
          heroku_email: "cmilfont@gmail.com"
          healthcheck: "https://payments-prodoops.herokuapp.com/s"
          checkstring: "Hello World!"