name: Pull Request Opened

on:
  pull_request:
    types:
      - opened
    branches:
      - '**'

jobs:
  
  notify:
    
    name: Notify Adora
    runs-on: ubuntu-latest

    steps:

      - name: Invoke Pull request opened hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_type: 'json-extended'
          webhook_url: ${{ secrets.WEBHOOK_START_URL }}
          webhook_secret: s3cr4t
          data: '{"ref":"${{github.event.pull_request.head.ref}}", "eventType": "START_CYCLE", "name" : "Review Time" }'
